### ISSUE TITLE
Can not assign dict whos key is not string as module attribute

### ISSUE THREAD

**Issue by wztdream** [google/flax#1925]
Hi,
It seems current flax.linen not allow assign a dict with non-string keys to the module attribute.
See below simple example:
it will trigger error:
`AssertionError: A state dict must only have string keys.`

Questions:
1. Is it an intended behavior? Why?
2. If it is intended, is there any work around? As it is quite possible we need assign the information contained by a dict to the module, and the key of the dict may not string.

```python

import flax.linen as nn
import jax
import jax.numpy as jnp


class Foo(nn.Module):
    def setup(self):
        self.a = {(1, 2): 3} # here the dict using tuple as key

    @nn.compact
    def __call__(self, x):
        return x


foo = Foo()
rng = jax.random.PRNGKey(0)
x = jnp.ones(shape=(3, 3))
vars = foo.init({"params": rng}, x)
out = foo.apply(vars, x)
print(out)
```

**Comment by jheek** [comment]
This should be fixed

**Comment by marcvanzee** [comment]
@jheek just tried this in a public Colab and installed flax from main, but the problem still seems to be there.

**Comment by levskaya** [comment]
It's because we traverse any assignment looking for Module leaves and have overly strict requirements on the structure of the tree (e.g. string keys) for any leaf Module and that's spilling over as a constraint on any leaf type.

**Comment by gszep** [comment]
this is not fixed and should be re-opened?

**Comment by muhrin** [comment]
@gszep , indeed, this has been fixes for the case that the OP outlined, but having non-str keys in the state (as opposed to the parameters) still doesn't work, e.g.:

```
import flax.linen as nn
import jax
import jax.numpy as jnp

a = {1: 2}

class Foo(nn.Module):
  def setup(self):
    self.a = FrozenDict(a)  # int as key.

  @nn.compact
  def __call__(self, x):
    return self.a[x]

foo = Foo()
x = 1
params = foo.init(random.key(0), x)
assert foo.apply(params, x) == a[x]
```
or
```
class Foo(nn.Module):
  a: dict[int, int]  # int as key.

  @nn.compact
  def __call__(self, x):
    return self.a[x]

a = {1: 2}
foo = Foo(a)
x = 1
params = foo.init(random.key(0), x)
assert foo.apply(params, x) == a[x]
```

I'm creating a PR that will address this as I need this ability for my code.
